[package]
name = "shmem-queue"
version = "0.1.0"
edition = "2018"

[dependencies]
log = "0.4.0"
env_logger = "0.9.0"
libc = "0.2.109"
cstr_core = "0.2.4"

[dev-dependencies]
shmem-queue = { path = "../shmem-queue" }
nix = "0.23.0"